{% set version = "2.1.1" %}

package:
  name: pygdp
  version: {{ version }}

source:
  git_url: https://github.com/ocefpaf/pyGDP.git
  git_branch: README
  sha256: 7d59394de088210befac33964e545bc4c160ecd05e7207bba43bd696cc890b80

build:
  number: 0
  script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - owslib
    - lxml

test:
  imports:
    - pygdp.pyGDP

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: Public Domain
  summary: 'Python interface to facilitate working with USGS-CIDA Geo Data Portal web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ayan-usgs
