{% set version = "2.1.2" %}

package:
  name: pygdp
  version: {{ version }}

source:
  url: https://github.com/USGS-CIDA/pyGDP/archive/v{{ version }}.tar.gz
  sha256: a0489b0fb48b1b9f81fbc6cc0518c8bcb784e69ceb696503463b3685b9dee7e2

build:
  number: 0
  script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - owslib
    - lxml

test:
  imports:
    - pyGDP

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: Public Domain
  summary: 'Python interface to facilitate working with USGS-CIDA Geo Data Portal web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ayan-usgs
    - rsignell-usgs
