{% set version = "2.1.2" %}

package:
  name: pygdp
  version: {{ version }}

source:
  git_url: https://github.com/USGS-CIDA/pyGDP.git
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - owslib
    - lxml

test:
  imports:
    - pyGDP

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: Public Domain
  summary: 'Python interface to facilitate working with USGS-CIDA Geo Data Portal web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ayan-usgs
    - rsignell-usgs
