travis:
  secure:
    BINSTAR_TOKEN: OxHD2mVPxD4lv0bO1z730jc1IRbBGilNWXuz+H1bNOC6M8O4iswx+/TQnGqatu1whg67tZe1wRh8IRZINT1rhSBvG4rSZ3C7nDeTR+VM1boNYWxUJ6R0464wmaP103LPLEEvjZ2ZXzgEhj3BgFnm2cEa5HHzq6CS3iJ6MyX5f7EuLu4NbIMHY979yflEGPmDzWSpXJNI43aAihfQGeZLdtS+96QPouv9gJK17FmFVyriUGUGJLVFbPSmyfV/sKbxf5TR6KJ3uEHyC4MFc8KLqprjOGxd//5hQ4BtE8Riare9vjRABh4NZMRZcTVcLi34ayAAgexQITwiTh5h3vKFyTT5Zq7IeKnCoS3THDPWh66T/FMHwvw2KwQbmMHSKUeb1w0diOT+h+Hpw73e33jbV/u0svCtwqBwwS6UbThLdsu2YPqCmHHjgqeBkTqBvhPUhnLr7Ncd8lHO+pH6ticc98O9YM0tRNz/+REuZ5IUC0WBNlC49piofCS5NiULw6tZqSBFpTFMmecEYmWzTqkOB8lLV/2l+VqFh44YWH5dlrq/O+EST/O0EY+Q4V/oGUZv9Zgn3FPUHIrQl3HVQBYWzauliW024SM4R/qGLh2DHbV50hjYesVRTvCNI7XtusX1FLMOo8dGqOyhXq9+Yz9YkrLCaDm/xEHUnfysgNCZWvw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
